Fix/replaceRequest
LivePersonInc/faas-client-node pull request #85
Opened 2022-09-13 07:54 UTC by chrbrt

- removed promise-request
+ added got as fetch client
– reworked unit test to use nock for mocking backend

2022-09-21 08:56 UTC, Templum requested changes

2022-09-21 08:56 UTC, Templum commented on src/client/client.ts
> +            return 0;
```suggestion
            return computedValue ? attemptCount * 350 : 0;
```

2022-09-21 08:56 UTC, Templum commented on src/helper/csdsClient.ts
> +      const {baseURIs} = body;
I believe this is undeeded you can set got to just resolve the body. There is no point in not doing that as we throw on HTTP errors anyways

2022-11-07 15:36 UTC, busybeaver commented on .github/workflows/unit-test.yml
> +on:
Should the unit-tests (which I assume run rather quickly) also run on the default/master branch? And not only on PRs?

2022-11-07 15:42 UTC, busybeaver commented on package.json
>      "request": "^2.88.2",
```suggestion

```

I guess we should remove the dependency since we are replacing it. Some for `request-promise`.

2022-11-07 15:45 UTC, busybeaver commented on src/client/baseClient.ts
> +        statusCode: statusCode,
```suggestion
        statusCode,
```

2022-11-07 15:46 UTC, busybeaver commented on src/client/baseClient.ts
> +          statusCode: statusCode,
```suggestion
          statusCode,
```

2022-11-07 15:48 UTC, busybeaver commented on src/client/client.ts
> +import {RequestError, RetryObject} from 'got';
It's optional, but we could use `import type` here, since we are just importing types here, right?

2022-11-08 11:28 UTC, merged